### ISSUE TITLE
Clarification: Max of two skills per Agent Group?

### ISSUE THREAD

**Issue by alapolloni** [A-Herzog/Callcenter-Simulator#1]
Hi, 
Am I understanding correctly that there are a maximum of two skills per Agent Group?
Thanks!

**Comment by A-Herzog** [comment]
Hi Alex Apolloni,

No, you can have as many skills for an agent group as you want to. Each agent group has exactly one skill level. And a skill level is a set of one or more skills. The idea using skill levels is, you can reuse them for multiple agent groups and do not need to redefine the same set of skills for different groups.

Also see the red and the orange box on this schematic model:
https://a-herzog.github.io/Callcenter-Simulator/CallcenterSimulatorModell_en.pdf

Greetings,
  Alexander Herzog
