### ISSUE TITLE
Confuse in General data menu> optimization group> optimizer item

### ISSUE THREAD

**Issue by fdvlpr** [A-Herzog/Callcenter-Simulator#4]
Hello, what are the difference between "on call basis" and "on client basis" in call center simulator?

**Comment by A-Herzog** [comment]
If a customer has to start three attempts to be served (2x call cancelation due to a too long waiting time; success in the third attempts), we have on client basis 1 client and 1 client was successful (100%). On call basis we have 3 calls and only one was successful (33.3%).

**Comment by fdvlpr** [comment]
The distribution of our calls is different every day, how can we define days with different distribution? Should a new model be created for each day of the year?

**Comment by A-Herzog** [comment]
Each model describes one day. The main idea is to model and analysis individual (typical) days. Call center simulator is a tool for analyzing general correlation, not for day to day forecasting etc. If serval days are coupled for example via back-office backlogs, you can use a connected optimization carrying over not yet completed backlog tasks from one day to another.

**Comment by fdvlpr** [comment]
I need help regarding the Load table item in the Data group. Please guide me through creating a template. What is a template's structure? Could you please send me a sample template so I can better understand?

**Comment by A-Herzog** [comment]
The "Load table" functions allows to load any model property from a free form table. This means you can use table data generated by other programs. In the "Load table" view you can add row to the list of data via the "Add" button. In each row you can define one property to be loaded.

For example if you use the small built-in example model as base and you have a table where the number of fresh call for "Clients (topic A)" is given in cell B3, you can setup
Typre="Number of fresh calls (single value)"
Parameter="Client (topic A)"
Start cell="B3"
End cell="B3"

Clicking on "Load data" will load value B3 from the external table and use it as the number of fresh calls for the client type "Client (topic A)" in the model. The New/Load/Save buttons allows to save such a setup (may be consisting later of many rows i.e. many things to load) for later use.

So if you get for example a new forecast for next month in form of a table and you already have a structural model, you can import the new numerical values with one click using the pre-defined table loading template.
